export const STAGES = [
  "Prospecting",
  "Qualification",
  "Proposal",
  "Negotiation",
  "Won",
  "Lost",
] as const;

export type Stage = (typeof STAGES)[number];

export type Opportunity = {
  id: string;
  name: string;
  account: string;
  stage: Stage;
  amount: number;
  closeDate: string; // ISO yyyy-mm-dd
  owner: string;
  nameOfSc?: string; // SE assigned to this opp (Snowflake NAME_OF_SC); absent on mock records
  scNotes: string;
  nextSteps: string; // AE Notes (Snowflake NEXT_STEP_C) — free text, not a list
  managerNotes: string;
  scManagerNotes: string;
  scEngagementType?: string;
  productSpecialistNotes?: string;
  dScore: number; // 0-100
  lastUpdateDate: string | null; // Parsed from SC Notes - most recent date mentioned
  recentDScoreDate?: string; // mock-data-only; live opps derive the D-Score history end date from lastUpdateDate/closeDate
  dScoreDelta: number;
};

export const OWNERS = [
  "Sarah Jenkins",
  "Marcus Thorne",
  "David Kim",
  "Elena Rodriguez",
  "Priya Patel",
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "OPP-94821",
    name: "Acme Global Expansion",
    account: "Acme Corp",
    stage: "Negotiation",
    amount: 142000,
    closeDate: "2026-07-12",
    owner: "Sarah Jenkins",
    scNotes:
      "Technical validation complete. Customer requested a custom integration with their legacy ERP. We have a clear path to MVP but need to confirm resource availability for Q3 implementation.",
    nextSteps: "Send updated MSA to Legal; Schedule sync with Product (ERP API)",
    managerNotes:
      "Sarah has strong champion support in the CTO office. Probability is high if we can handle the compliance review by month end.",
    scManagerNotes:
      "Ensure the implementation costs are fully loaded in the proposal. Don't discount service hours on this one.",
    dScore: 82,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-12",
    dScoreDelta: 5,
  },
  {
    id: "OPP-94822",
    name: "Nebula Data Platform",
    account: "Nebula Systems",
    stage: "Proposal",
    amount: 64500,
    closeDate: "2026-08-01",
    owner: "Marcus Thorne",
    scNotes:
      "POC delivered successfully across 3 data sources. Buying committee aligned on the technical fit; pricing review is the remaining blocker.",
    nextSteps: "Deliver final pricing sheet; Confirm SOC2 documentation",
    managerNotes: "Watch for procurement delay — they have a 6-week vendor onboarding cycle.",
    scManagerNotes: "Bundle the migration services to justify list pricing.",
    dScore: 58,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-18",
    dScoreDelta: -2,
  },
  {
    id: "OPP-94823",
    name: "CloudScale Renewal+",
    account: "CloudScale Corp",
    stage: "Qualification",
    amount: 210000,
    closeDate: "2026-06-22",
    owner: "Sarah Jenkins",
    scNotes: "Renewal at risk. Champion left the org last month; need to re-establish executive sponsor.",
    nextSteps: "Map new buying committee; Request exec sponsor intro",
    managerNotes: "Escalate to VP if no exec contact secured within 2 weeks.",
    scManagerNotes: "Treat as new logo motion until we re-anchor the relationship.",
    dScore: 34,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-20",
    dScoreDelta: -12,
  },
  {
    id: "OPP-94824",
    name: "Ironwood Fleet Telemetry",
    account: "Ironwood Logistics",
    stage: "Won",
    amount: 12000,
    closeDate: "2026-04-20",
    owner: "David Kim",
    scNotes: "Pilot signed. Limited scope, but a strong reference customer for the logistics vertical.",
    nextSteps: "Kickoff scheduled for May 1; Loop in CSM",
    managerNotes: "Strong foothold — line up expansion conversation in Q4.",
    scManagerNotes: "Document the integration patterns for reuse.",
    dScore: 74,
    lastUpdateDate: null,
    recentDScoreDate: "2026-04-22",
    dScoreDelta: 3,
  },
  {
    id: "OPP-94825",
    name: "Stellar Analytics Tier 2",
    account: "Stellar Tech",
    stage: "Proposal",
    amount: 89000,
    closeDate: "2026-09-10",
    owner: "Sarah Jenkins",
    scNotes: "Evaluating us against two competitors. Differentiation is governance + audit features.",
    nextSteps: "Run governance demo; Share Forrester comparison brief",
    managerNotes: "Decision committee meets June 15.",
    scManagerNotes: "Push for a paid POC to lock out competitors.",
    dScore: 42,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-15",
    dScoreDelta: 0,
  },
  {
    id: "OPP-94826",
    name: "FinStream Compliance Module",
    account: "FinStream Inc",
    stage: "Negotiation",
    amount: 15500,
    closeDate: "2026-06-05",
    owner: "Marcus Thorne",
    scNotes: "Down to redlines. Legal review on indemnification clauses.",
    nextSteps: "Legal response by EOW; Confirm start date",
    managerNotes: "Small ticket but strategic — first finance vertical win.",
    scManagerNotes: "Hold the line on uptime SLA wording.",
    dScore: 91,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-22",
    dScoreDelta: 4,
  },
  {
    id: "OPP-94827",
    name: "Vertex Media Migration",
    account: "Vertex Media",
    stage: "Qualification",
    amount: 45000,
    closeDate: "2026-08-18",
    owner: "Priya Patel",
    scNotes: "Discovery complete. Migrating off a homegrown system; scope is well defined.",
    nextSteps: "Send architecture diagram; Schedule security review",
    managerNotes: "Champion is the new VP Eng — strong relationship signal.",
    scManagerNotes: "Standard migration package should fit.",
    dScore: 68,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-19",
    dScoreDelta: 6,
  },
  {
    id: "OPP-94828",
    name: "Capital Bank Security Suite",
    account: "Capital Bank",
    stage: "Proposal",
    amount: 310000,
    closeDate: "2026-10-01",
    owner: "Elena Rodriguez",
    scNotes: "Large deal. Multiple stakeholders across InfoSec, IT, and Risk. Procurement-driven.",
    nextSteps: "Submit RFP response; Schedule InfoSec deep dive",
    managerNotes: "Forecast as commit only after RFP scoring.",
    scManagerNotes: "Bring solutions architect to InfoSec session.",
    dScore: 47,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-21",
    dScoreDelta: 2,
  },
  {
    id: "OPP-94829",
    name: "Skyline Cloud Native Upgrade",
    account: "Skyline Dev",
    stage: "Negotiation",
    amount: 140000,
    closeDate: "2026-06-30",
    owner: "David Kim",
    scNotes: "Strong technical fit. Pricing approved internally. Awaiting customer board sign-off.",
    nextSteps: "Confirm board outcome; Prep onboarding plan",
    managerNotes: "High confidence close this quarter.",
    scManagerNotes: "Pre-stage CSM for fast handoff.",
    dScore: 92,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-23",
    dScoreDelta: 1,
  },
  {
    id: "OPP-94830",
    name: "Bloom Marketing Automations",
    account: "Bloom Agency",
    stage: "Won",
    amount: 55000,
    closeDate: "2026-03-15",
    owner: "Priya Patel",
    scNotes: "Closed Q1. Expansion conversation already in motion for additional seats.",
    nextSteps: "Schedule QBR; Identify expansion sponsor",
    managerNotes: "Reference candidate for marketing vertical.",
    scManagerNotes: "Capture case study within 60 days.",
    dScore: 98,
    lastUpdateDate: null,
    recentDScoreDate: "2026-04-01",
    dScoreDelta: 0,
  },
  {
    id: "OPP-94831",
    name: "Local Threads Pilot",
    account: "Local Threads",
    stage: "Lost",
    amount: 12500,
    closeDate: "2026-02-28",
    owner: "Marcus Thorne",
    scNotes: "Budget pulled mid-cycle. Champion remains warm; revisit Q4.",
    nextSteps: "Quarterly check-in scheduled; Send relevant case study",
    managerNotes: "Move to nurture. Not a fit until they raise next round.",
    scManagerNotes: "Tag for nurture; revisit FY27.",
    dScore: 8,
    lastUpdateDate: null,
    recentDScoreDate: "2026-03-01",
    dScoreDelta: -20,
  },
  {
    id: "OPP-94832",
    name: "Maersk Logistics Expansion",
    account: "Maersk Group",
    stage: "Prospecting",
    amount: 85000,
    closeDate: "2026-11-15",
    owner: "David Kim",
    scNotes: "Early-stage. Inbound lead from website demo. Discovery scheduled.",
    nextSteps: "Run discovery call; Qualify budget and authority",
    managerNotes: "Don't over-invest until qualification confirms fit.",
    scManagerNotes: "Standard discovery deck — no SC time yet.",
    dScore: 32,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-10",
    dScoreDelta: 0,
  },
  {
    id: "OPP-94833",
    name: "FinTech Platform Migration",
    account: "FinTech Solutions",
    stage: "Prospecting",
    amount: 120000,
    closeDate: "2026-10-20",
    owner: "Elena Rodriguez",
    scNotes: "Outbound-sourced. CTO is engaged; aligning on evaluation criteria.",
    nextSteps: "Send evaluation framework; Confirm POC scope",
    managerNotes: "Promising. Allocate SC after POC scope confirmed.",
    scManagerNotes: "Cap POC at 3 weeks.",
    dScore: 55,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-17",
    dScoreDelta: 5,
  },
  {
    id: "OPP-94834",
    name: "Atlas Insurance Underwriting",
    account: "Atlas Insurance",
    stage: "Qualification",
    amount: 178000,
    closeDate: "2026-09-25",
    owner: "Elena Rodriguez",
    scNotes: "Complex compliance landscape. Need to validate data residency requirements.",
    nextSteps: "Confirm data residency; Schedule compliance Q&A",
    managerNotes: "Strategic deal for insurance vertical entry.",
    scManagerNotes: "Loop in compliance SME for next call.",
    dScore: 61,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-20",
    dScoreDelta: 3,
  },
  {
    id: "OPP-94835",
    name: "Helix Bio Research Suite",
    account: "Helix Biotech",
    stage: "Proposal",
    amount: 96000,
    closeDate: "2026-07-30",
    owner: "Priya Patel",
    scNotes: "Custom research workflow validated. Awaiting procurement engagement.",
    nextSteps: "Procurement intake form; Confirm fiscal calendar",
    managerNotes: "Fiscal year ends Sept — push to close before then.",
    scManagerNotes: "Offer Q3 incentive if needed to accelerate.",
    dScore: 70,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-19",
    dScoreDelta: 2,
  },
  {
    id: "OPP-94836",
    name: "Northwind ERP Connector",
    account: "Northwind Traders",
    stage: "Negotiation",
    amount: 38000,
    closeDate: "2026-06-10",
    owner: "Marcus Thorne",
    scNotes: "Standard connector deal. Contract review in legal.",
    nextSteps: "Resolve auto-renewal clause",
    managerNotes: "Likely close this month.",
    scManagerNotes: "Standard terms acceptable.",
    dScore: 84,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-21",
    dScoreDelta: 1,
  },
  {
    id: "OPP-94837",
    name: "Quantum Labs Platform",
    account: "Quantum Labs",
    stage: "Lost",
    amount: 220000,
    closeDate: "2026-04-05",
    owner: "Sarah Jenkins",
    scNotes: "Lost to incumbent. Price was not the issue — switching costs were too high.",
    nextSteps: "Schedule 6-month revisit",
    managerNotes: "Good qualification despite the loss. Document learnings.",
    scManagerNotes: "Brief the team on the incumbent's stickiness factors.",
    dScore: 12,
    lastUpdateDate: null,
    recentDScoreDate: "2026-04-06",
    dScoreDelta: -30,
  },
  {
    id: "OPP-94838",
    name: "Pioneer Health Records",
    account: "Pioneer Health",
    stage: "Qualification",
    amount: 265000,
    closeDate: "2026-12-01",
    owner: "Elena Rodriguez",
    scNotes: "HIPAA workflow review in progress. Long sales cycle expected.",
    nextSteps: "Sign BAA; Map compliance gap list",
    managerNotes: "Forecast for next quarter, not this one.",
    scManagerNotes: "Pull in compliance team weekly.",
    dScore: 52,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-18",
    dScoreDelta: 4,
  },
  {
    id: "OPP-94839",
    name: "Beacon Education Rollout",
    account: "Beacon Education",
    stage: "Prospecting",
    amount: 41000,
    closeDate: "2026-08-25",
    owner: "Priya Patel",
    scNotes: "Education vertical pilot. Budget unconfirmed.",
    nextSteps: "Confirm fiscal availability; Run product overview",
    managerNotes: "Education deals tend to slip — set conservative date.",
    scManagerNotes: "Reuse education vertical demo.",
    dScore: 38,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-14",
    dScoreDelta: 1,
  },
  {
    id: "OPP-94840",
    name: "Granite Manufacturing IoT",
    account: "Granite Manufacturing",
    stage: "Proposal",
    amount: 132000,
    closeDate: "2026-09-05",
    owner: "David Kim",
    scNotes: "On-prem deployment. Proposal includes managed services line.",
    nextSteps: "Confirm on-prem hardware list; Schedule install planning call",
    managerNotes: "Margin is thin — verify services pricing.",
    scManagerNotes: "Loop in deployment lead before final pricing.",
    dScore: 66,
    lastUpdateDate: null,
    recentDScoreDate: "2026-05-22",
    dScoreDelta: 2,
  },
];
